# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  pigImGui_config = debug

else ifeq ($(config),release)
  pigImGui_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := pigImGui

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

pigImGui:
ifneq (,$(pigImGui_config))
	@echo "==== Building pigImGui ($(pigImGui_config)) ===="
	@${MAKE} --no-print-directory -C . -f pigImGui.make config=$(pigImGui_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f pigImGui.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   pigImGui"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"